# Generated by Django 4.0.5 on 2022-06-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task',
            new_name='title',
        ),
    ]
