# Generated by Django 4.0.5 on 2022-06-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_rename_task_task_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('done', '-created')},
        ),
        migrations.AlterField(
            model_name='task',
            name='info',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
